import React, { createContext, useState, useContext } from 'react';

// Translation Dictionary (Mock Data)
const translations = {
    en: {
        logo: 'ConnectGrower',
        home: 'Home',
        chat: 'Global Chat',
        forum: 'Farm Insight',
        heroTitle: 'Connect, Share, Grow Together 🌱',
        heroDesc: "The world's first global community for farmers. Join us to share insights, trade tips, and grow your farming network.",
        joinBtn: 'Join the Community',
        updatesTitle: 'Latest Updates from Farmers 🌾',
        post1: 'Today we harvested 500kg of organic tomatoes! 🍅 The weather was perfect.',
        post2: 'Trying out a new irrigation system for my corn fields. Any tips? 🌽',
        post3: 'Harvest season for tangerines is starting next week! 🍊 Excited but nervous.',
        likes: 'Sun ☀️',
        comment: 'Branch 🌿',
        translate: 'Translate',
        chatTitle: 'Global Farmers Chat 💬',
        chatPlaceholder: 'Type a message (auto-translated)...',
        send: 'Send',
        forumTitle: 'Farm Insight Board (Coming Soon) 🚜',
        forumDesc: 'Share your farming knowledge and ask questions here!',
        forumSoon: 'We are building this feature for you!',
        forumDetail: 'Soon you will be able to post detailed guides and questions.',

        // Auth
        login: 'Log In',
        signup: 'Sign Up',
        createAccount: 'Create Account',
        welcomeBack: 'Welcome Back! 👋',
        fullName: 'Full Name',
        emailPlaceholder: 'name@example.com',
        passwordPlaceholder: '********',
        confirmPassword: 'Confirm Password',
        processing: 'Processing...',
        or: 'OR',
        signInGoogle: 'Sign in with Google',

        // Profile
        myProfile: 'My Profile',
        logout: 'Logout',
        editProfile: 'Edit Profile',
        saveProfile: 'Save Profile',
        cancel: 'Cancel',
        nickname: 'Nickname',
        farmName: 'Farm Name',
        farmNamePlaceholder: 'Farm Name (e.g., Sunny Orchard)',
        location: 'Location',
        locationPlaceholder: 'Location (e.g., Napa Valley, CA)',
        bio: 'Bio',
        bioPlaceholder: 'Bio: Tell us about your farming journey...',
        noBio: "No bio yet. Tap 'Edit Profile' to introduce yourself!",
        threads: 'Threads',
        replies: 'Replies',
        noPosts: "No sprouts planted yet.",

        // Post
        translated: 'Translated',
        viewTranslated: 'View Translated',
        viewOriginal: 'See Original',
        translatedFrom: 'Translated from original',
        replyTo: 'Branch out to',
        postBtn: 'Plant 🌱',
        startConversation: 'Grow a new branch...',
        sunFeedback: 'You cast a Sun beam! ☀️',
        grapeMember: 'CitrusGrowers Member 🍊',

        // Topics & Prompts
        topic_general: 'General',
        topic_harvest: 'Harvest 🧺',
        topic_issue: 'Issue ⚠️',
        topic_market: 'Market 💰',
        topic_question: 'Question ❓',
        ph_general: 'Share your farming story...',
        ph_harvest: 'How is your harvest going? Share yield, quality, or photos! 🍊',
        ph_issue: 'Describe the pest, disease, or challenge you are facing...',
        ph_market: 'What are the current prices or market trends in your area?',
        ph_question: 'Ask the community for advice...',
        filter_all: 'All',
        filter_harvest: 'Harvests',
        filter_issue: 'Issues',
        filter_market: 'Market'
    },
    ko: {
        logo: 'ConnectGrower',
        home: '홈',
        chat: '글로벌 채팅',
        forum: '농사 지혜',
        heroTitle: '연결하고, 공유하고, 함께 성장해요 🌱',
        heroDesc: '전 세계 농부들을 위한 최초의 글로벌 커뮤니티입니다. 아이디어를 나누고, 팁을 공유하며, 함께 성장하세요.',
        joinBtn: '커뮤니티 가입하기',
        updatesTitle: '농부들의 최신 소식 🌾',
        post1: '오늘 유기농 토마토 500kg 수확했어요! 🍅 날씨가 정말 완벽했네요.',
        post2: '옥수수 밭에 새로운 관개 시스템을 써보는 중이에요. 팁 있으신 분? 🌽',
        post3: '다음 주부터 감귤 수확 시작해요! 🍊 설레기도 하고 긴장되네요.',
        likes: '햇살 ☀️',
        comment: '가지 🌿',
        translate: '번역하기',
        chatTitle: '글로벌 농부 채팅방 💬',
        chatPlaceholder: '메시지를 입력하세요 (자동 번역됨)...',
        send: '전송',
        forumTitle: '농사 지혜 게시판 (오픈 예정) 🚜',
        forumDesc: '여기에 농사 노하우를 공유하고 질문해보세요!',
        forumSoon: '여러분을 위해 열심히 만들고 있어요!',
        forumDetail: '곧 자세한 가이드와 질문을 올릴 수 있게 될 거예요.',

        // Auth
        login: '로그인',
        signup: '회원가입',
        createAccount: '계정 생성',
        welcomeBack: '환영합니다! 👋',
        fullName: '이름',
        emailPlaceholder: '이메일 주소',
        passwordPlaceholder: '비밀번호',
        confirmPassword: '비밀번호 확인',
        processing: '처리 중...',
        or: '또는',
        signInGoogle: 'Google로 로그인',

        // Profile
        myProfile: '내 프로필',
        logout: '로그아웃',
        editProfile: '프로필 수정',
        saveProfile: '프로필 저장',
        cancel: '취소',
        nickname: '닉네임',
        farmName: '농장 이름',
        farmNamePlaceholder: '농장 이름 (예: 햇살 감귤밭)',
        location: '위치',
        locationPlaceholder: '위치 (예: 경북 영천)',
        bio: '소개',
        bioPlaceholder: '소개: 당신의 농사 이야기를 들려주세요...',
        noBio: "아직 소개가 없습니다. '프로필 수정'을 눌러 자신을 소개해보세요!",
        threads: '스레드',
        replies: '답글',
        noPosts: "아직 심은 새싹이 없습니다.",

        // Post
        translated: '번역됨',
        viewTranslated: '번역 보기',
        viewOriginal: '원문 보기',
        translatedFrom: '원문에서 번역됨',
        replyTo: '가지 치기:',
        postBtn: '심기 🌱',
        startConversation: '새로운 가지를 쳐보세요...',
        sunFeedback: '햇살을 비추었습니다! ☀️',
        grapeMember: '감귤 재배자 멤버 🍊',

        // Topics & Prompts
        topic_general: '일반',
        topic_harvest: '수확 🧺',
        topic_issue: '문제/병해충 ⚠️',
        topic_market: '시장/가격 💰',
        topic_question: '질문 ❓',
        ph_general: '농사 이야기를 공유해주세요...',
        ph_harvest: '수확은 어떠신가요? 수확량이나 품질 이야기를 들려주세요! 🍊',
        ph_issue: '겪고 계신 병해충이나 어려움을 설명해주세요...',
        ph_market: '지역의 현재 시세나 시장 동향은 어떤가요?',
        ph_question: '커뮤니티에 조언을 구해보세요...',
        filter_all: '전체',
        filter_harvest: '수확',
        filter_issue: '문제',
        filter_market: '시장'
    },
    ja: {
        logo: 'ConnectGrower',
        home: 'ホーム',
        chat: 'グローバルチャット',
        forum: '農業インサイト',
        heroTitle: 'つながり、共有し、共に成長しよう 🌱',
        heroDesc: '世界中の農家のための初のグローバルコミュニティです。アイデアを共有し、ヒントを交換し、共に成長しましょう。',
        joinBtn: 'コミュニティに参加',
        updatesTitle: '農家からの最新情報 🌾',
        post1: '今日、有機トマト500kgを収穫しました！🍅 天気は最高でした。',
        post2: 'トウモロコシ畑で新しい灌漑システムを試しています。何かアドバイスはありますか？🌽',
        post3: '来週からみかんの収穫シーズンが始まります！🍊 ワクワクするけど緊張もします。',
        likes: '太陽 ☀️',
        comment: '枝 🌿',
        translate: '翻訳',
        chatTitle: 'グローバル農家チャット 💬',
        chatPlaceholder: 'メッセージを入力（自動翻訳）...',
        send: '送信',
        forumTitle: '農業インサイト掲示板（近日公開）🚜',
        forumDesc: 'あなたの農業ノウハウを共有し、ここで質問しましょう！',
        forumSoon: '現在、この機能を構築中です！',
        forumDetail: '間もなく詳細なガイドや質問を投稿できるようになります。',

        // Auth
        login: 'ログイン',
        signup: 'サインアップ',
        createAccount: 'アカウント作成',
        welcomeBack: 'おかえりなさい！👋',
        fullName: '名前',
        emailPlaceholder: 'メールアドレス',
        passwordPlaceholder: 'パスワード',
        confirmPassword: 'パスワード確認',
        processing: '処理中...',
        or: 'または',
        signInGoogle: 'Googleでログイン',

        // Profile
        myProfile: 'プロフィール',
        logout: 'ログアウト',
        editProfile: 'プロフィール編集',
        saveProfile: '保存',
        cancel: 'キャンセル',
        nickname: 'ニックネーム',
        farmName: '農場名',
        farmNamePlaceholder: '農場名（例：サニーオーチャード）',
        location: '場所',
        locationPlaceholder: '場所（例：ナパバレー）',
        bio: '自己紹介',
        bioPlaceholder: '自己紹介：あなたの農業の話を聞かせてください...',
        noBio: "自己紹介はまだありません。「プロフィール編集」をタップして自己紹介しましょう！",
        threads: 'スレッド',
        replies: '返信',
        noPosts: "まだ芽が出ていません。",

        // Post
        translated: '翻訳済み',
        viewTranslated: '翻訳を見る',
        viewOriginal: '原文を見る',
        translatedFrom: '原文から翻訳',
        replyTo: '枝分かれ:',
        postBtn: '植える 🌱',
        startConversation: '新しい枝を伸ばしましょう...',
        sunFeedback: '日差しを届けました！ ☀️',
        grapeMember: 'みかん栽培メンバー 🍊',

        // Topics & Prompts
        topic_general: '一般',
        topic_harvest: '収穫 🧺',
        topic_issue: '課題/病害虫 ⚠️',
        topic_market: '市場/価格 💰',
        topic_question: '質問 ❓',
        ph_general: 'あなたの農業の話を共有してください...',
        ph_harvest: '収穫の調子はどうですか？収穫量や品質について教えてください！🍊',
        ph_issue: '直面している病害虫や課題について説明してください...',
        ph_market: 'あなたの地域の現在の価格や市場動向はどうですか？',
        ph_question: 'コミュニティにアドバイスを求めてみましょう...',
        filter_all: 'すべて',
        filter_harvest: '収穫',
        filter_issue: '課題',
        filter_market: '市場'
    },
    it: {
        logo: 'ConnectGrower',
        home: 'Home',
        chat: 'Chat Globale',
        forum: 'Approfondimenti',
        heroTitle: 'Connettiti, Condividi, Cresci Insieme 🌱',
        heroDesc: 'La prima community globale per agricoltori. Unisciti a noi per condividere idee, scambiare consigli e far crescere la tua rete.',
        joinBtn: 'Unisciti alla Community',
        updatesTitle: 'Ultimi Aggiornamenti dagli Agricoltori 🌾',
        post1: 'Oggi abbiamo raccolto 500kg di pomodori biologici! 🍅 Il tempo era perfetto.',
        post2: 'Sto provando un nuovo sistema di irrigazione per i miei campi di mais. Qualche consiglio? 🌽',
        post3: 'La stagione della raccolta degli agrumi inizia la prossima settimana! 🍊 Eccitato ma nervoso.',
        likes: 'Sole ☀️',
        comment: 'Ramo 🌿',
        translate: 'Traduci',
        chatTitle: 'Chat Globale degli Agricoltori 💬',
        chatPlaceholder: 'Scrivi un messaggio (traduzione automatica)...',
        send: 'Invia',
        forumTitle: 'Bacheca Approfondimenti (Prossimamente) 🚜',
        forumDesc: 'Condividi le tue conoscenze agricole e fai domande qui!',
        forumSoon: 'Stiamo costruendo questa funzionalità per te!',
        forumDetail: 'Presto potrai pubblicare guide dettagliate e domande.',

        // Auth
        login: 'Accedi',
        signup: 'Iscriviti',
        createAccount: 'Crea Account',
        welcomeBack: 'Bentornato! 👋',
        fullName: 'Nome Completo',
        emailPlaceholder: 'indirizzo@esempio.com',
        passwordPlaceholder: '********',
        confirmPassword: 'Conferma Password',
        processing: 'Elaborazione...',
        or: 'O',
        signInGoogle: 'Accedi con Google',

        // Profile
        myProfile: 'Il mio Profilo',
        logout: 'Esci',
        editProfile: 'Modifica Profilo',
        saveProfile: 'Salva Profilo',
        cancel: 'Annulla',
        nickname: 'Soprannome',
        farmName: 'Nome della Fattoria',
        farmNamePlaceholder: 'Nome della Fattoria (es. Agrumeto Soleggiato)',
        location: 'Posizione',
        locationPlaceholder: 'Posizione (es. Chianti, Italia)',
        bio: 'Biografia',
        bioPlaceholder: 'Biografia: Raccontaci la tua storia agricola...',
        noBio: "Nessuna biografia ancora. Tocca 'Modifica Profilo' per presentarti!",
        threads: 'Thread',
        replies: 'Risposte',
        noPosts: "Nessun germoglio piantato ancora.",

        // Post
        translated: 'Tradotto',
        viewTranslated: 'Vedi Traduzione',
        viewOriginal: 'Vedi Originale',
        translatedFrom: 'Tradotto dall\'originale',
        replyTo: 'Ramifica a',
        postBtn: 'Pianta 🌱',
        startConversation: 'Fai crescere un nuovo ramo...',
        sunFeedback: 'Hai mandato un raggio di Sole! ☀️',
        grapeMember: 'Membro Agrumicoltore 🍊',

        // Topics & Prompts
        topic_general: 'Generale',
        topic_harvest: 'Raccolto 🧺',
        topic_issue: 'Problema ⚠️',
        topic_market: 'Mercato 💰',
        topic_question: 'Domanda ❓',
        ph_general: 'Condividi la tua storia agricola...',
        ph_harvest: 'Come va il raccolto? Condividi quantità o qualità! 🍊',
        ph_issue: 'Descrivi il parassita o la sfida che stai affrontando...',
        ph_market: 'Quali sono i prezzi o le tendenze di mercato nella tua zona?',
        ph_question: 'Chiedi consiglio alla community...',
        filter_all: 'Tutti',
        filter_harvest: 'Raccolti',
        filter_issue: 'Problemi',
        filter_market: 'Mercato'
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    // Default language reverted to English ('en')
    const [language, setLanguage] = useState('en');

    const value = {
        language,
        setLanguage,
        t: (key) => translations[language][key] || key,
    };

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
